### ISSUE TITLE
Validate required arguments to DSL functions

### ISSUE THREAD

**Issue by jturkel** [salsify/avro-builder#15]
Attempting to generate a schema for the following DSL (note the `values` option isn't specified for the map) raises a `NoMethodError`

```
record :my_event do
  required :my_map, :map
end
```
The stack trace is:
```
NoMethodError: undefined method `serialize' for nil:NilClass
/Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/avro-builder-0.3.1/lib/avro/builder/types/map_type.rb:20:in `serialize'
/Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/avro-builder-0.3.1/lib/avro/builder/field.rb:80:in `serialized_type'
/Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/avro-builder-0.3.1/lib/avro/builder/field.rb:67:in `serialize'
/Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/avro-builder-0.3.1/lib/avro/builder/types/record_type.rb:57:in `block (2 levels) in to_h'
/Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/avro-builder-0.3.1/lib/avro/builder/types/record_type.rb:57:in `map'
/Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/avro-builder-0.3.1/lib/avro/builder/types/record_type.rb:57:in `block in to_h'
/Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/avro-builder-0.3.1/lib/avro/builder/schema_serializer_reference_state.rb:22:in `definition_or_reference'
/Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/avro-builder-0.3.1/lib/avro/builder/types/record_type.rb:50:in `to_h'
/Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/avro-builder-0.3.1/lib/avro/builder/dsl.rb:80:in `to_h'
/Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/avro-builder-0.3.1/lib/avro/builder/dsl.rb:85:in `to_json'
/Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/avro-builder-0.3.1/lib/avro/builder.rb:9:in `build'
/Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/salsify_avro-0.3.0/lib/salsify_avro/rake/avro_generate_task.rb:37:in `block (3 levels) in define'
/Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/salsify_avro-0.3.0/lib/salsify_avro/rake/avro_generate_task.rb:34:in `each'
/Users/jturkel/.rvm/gems/ruby-2.2.4@dandelion/gems/salsify_avro-0.3.0/lib/salsify_avro/rake/avro_generate_task.rb:34:in `block (2 levels) in define'
```

**Comment by tjwp** [comment]
This is not quite a simple as validating arguments because options can be supplied as arguments or via a block. I think the answer is to call a validation function after an object is built.
