### ISSUE TITLE
Include dsl file/line numbers in stack trace

### ISSUE THREAD

**Issue by jturkel** [salsify/avro-builder#23]
Errors in DSL files can result in stack traces like this:

```
ArgumentError: wrong number of arguments (given 1, expected 2..3)
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/gems/avro-builder-0.8.0/lib/avro/builder/dsl.rb:31:in `instance_eval'
(eval):11:in `block in initialize'
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/gems/avro-builder-0.8.0/lib/avro/builder/type_factory.rb:38:in `instance_eval'
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/gems/avro-builder-0.8.0/lib/avro/builder/type_factory.rb:38:in `block in create_and_configure_builtin_type'
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/gems/avro-builder-0.8.0/lib/avro/builder/type_factory.rb:35:in `tap'
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/gems/avro-builder-0.8.0/lib/avro/builder/type_factory.rb:35:in `create_and_configure_builtin_type'
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/gems/avro-builder-0.8.0/lib/avro/builder/dsl.rb:86:in `create_named_type'
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/gems/avro-builder-0.8.0/lib/avro/builder/dsl.rb:36:in `record'
(eval):3:in `initialize'
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/gems/avro-builder-0.8.0/lib/avro/builder/dsl.rb:31:in `instance_eval'
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/gems/avro-builder-0.8.0/lib/avro/builder/dsl.rb:31:in `initialize'
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/gems/avro-builder-0.8.0/lib/avro/builder.rb:10:in `new'
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/gems/avro-builder-0.8.0/lib/avro/builder.rb:10:in `build'
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/gems/salsify_avro-0.21.0/lib/salsify_avro/rake/avro_generate_task.rb:37:in `block (3 levels) in define'
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/gems/salsify_avro-0.21.0/lib/salsify_avro/rake/avro_generate_task.rb:34:in `each'
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/gems/salsify_avro-0.21.0/lib/salsify_avro/rake/avro_generate_task.rb:34:in `block (2 levels) in define'
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/bin/ruby_executable_hooks:15:in `eval'
/Users/jturkel/.rvm/gems/ruby-2.3.1@alerts-service/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => avro:generate
(See full trace by running task with --trace)
```
It would be helpful if calls to `instance_eval` included the source file to more easily track errors back to a line in a DSL file e.g. `/Users/jturkel/salsify/alerts-service/avro/dsl/com/salsify/alerts/events/alert_created_event_value.rb` rather than `(eval)`.

**Comment by tjwp** [comment]
For reference: http://ruby-doc.org/core-2.2.0/BasicObject.html#method-i-instance_eval
