### ISSUE TITLE
rake task exception when building dsl

### ISSUE THREAD

**Issue by steveburkett** [salsify/avro-builder#49]
Rake task fails to build avro files from dsl.  Using ruby-2.6.5.

Building this DSL

```
# <rails_root>/avro/dsl/example.rb
namespace 'com.example'

fixed :password, 8

enum :user_type, :ADMIN, :REGULAR

record :user do
  required :id, :long
  required :user_name, :string
  required :type, :user_type, default: :REGULAR
  required :pw, :password
  optional :full_name, :string
  required :nicknames, :array, items: :string
  required :permissions, :map, values: :bytes
end
```

running `be rake avro:generate` generates this error

```
Generating Avro schema from /Users/steveburkett/openstax/event-capture-api/avro/dsl/nudged.rb
rake aborted!
ArgumentError: wrong number of arguments (given 1, expected 0)
/Users/steveburkett/.rvm/gems/ruby-2.6.5@event-capture-api/gems/avro-builder-0.17.0/lib/avro/builder/dsl.rb:74:in `to_h'
/Users/steveburkett/.rvm/gems/ruby-2.6.5@event-capture-api/gems/avro-builder-0.17.0/lib/avro/builder/dsl.rb:74:in `to_h'
/Users/steveburkett/.rvm/gems/ruby-2.6.5@event-capture-api/gems/avro-builder-0.17.0/lib/avro/builder/dsl.rb:79:in `to_json'
/Users/steveburkett/.rvm/gems/ruby-2.6.5@event-capture-api/gems/avro-builder-0.17.0/lib/avro/builder/rake/avro_generate_task.rb:48:in `block (3 levels) in define'
/Users/steveburkett/.rvm/gems/ruby-2.6.5@event-capture-api/gems/avro-builder-0.17.0/lib/avro/builder/rake/avro_generate_task.rb:38:in `each'
/Users/steveburkett/.rvm/gems/ruby-2.6.5@event-capture-api/gems/avro-builder-0.17.0/lib/avro/builder/rake/avro_generate_task.rb:38:in `block (2 levels) in define'
/Users/steveburkett/.rvm/gems/ruby-2.6.5@event-capture-api/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Users/steveburkett/.rvm/gems/ruby-2.6.5@event-capture-api/bin/ruby_executable_hooks:24:in `eval'
/Users/steveburkett/.rvm/gems/ruby-2.6.5@event-capture-api/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by tjwp** [comment]
That's interesting. I've tried to reproduce this error a few different ways (Avro 1.8.2, 1.9.2, 1.10.0) and passing your example as both a string and as a block to the DSL. But it works in each of the permutations that I've tried.

Based on the error is there any chance that you have another gem loaded that is overriding the definition of `to_h` for objects?

**Comment by steveburkett** [comment]
does it work for you to put this as a file under avro/dsl/example.rb and
build it thru the rake task? i'm using ruby 2.6.5...switching to ruby 2.6.6
to see if that helps.

**Comment by tjwp** [comment]
I dropped it into avro/dsl/example.rb in an app using Ruby 2.6.5 and avro-builder v0.17.0 (as above) and it worked for me.

Is the repo where you're working on this public? If you want to push a branch, I'm happy to pull it down and take a quick look.

**Comment by steveburkett** [comment]
@tjwp i rebooted my mac and i dont see the problem anymore.  perhaps it was a ruby/rvm snafu. thanks so much for helping.  will close it now.
