### ISSUE TITLE
Issue with Ruby 2.6.5

### ISSUE THREAD

**Issue by SushmaShyam** [salsify/avro-builder#55]
The following basic example works with Ruby 2.6.2 but not with 2.6.5

```
require 'avro/builder'

Avro::Builder.build do
	namespace 'com.example'

	fixed :password, 8

	enum :user_type, :ADMIN, :REGULAR

	record :user do
	  required :id, :long
	  required :user_name, :string
	  required :type, :user_type, default: :REGULAR
	  required :pw, :password
	  optional :full_name, :string
	  required :nicknames, :array, items: :string
	  required :permissions, :map, values: :bytes
	end
end

```
Error:
```
Traceback (most recent call last):
 2: from schemas/example.rb:3:in `<main>'
 1: from /Users/sushma/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/avro-builder-0.17.0/lib/avro/builder.rb:17:in `build'
/Users/sushma/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/avro-builder-0.17.0/lib/avro/builder/dsl.rb:80:in `to_json': 
uninitialized constant Avro::Builder::DSL::JSON (NameError)
```

**Comment by tjwp** [comment]
Thank you for filing this issue. It looks like something changed between 2.6.2 and 2.6.5 so that the `json` gem that ships with ruby is no longer being loaded as a side effect.

The simplest workaround is to add `require 'json'` at the start of your example. I will update `avro-builder` to add this or a similar requirement in the future.
